name: gaz_test
description: Тестовое задание для *
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  flutter_screenutil: ^5.6.1
  get_it: ^7.2.0
  dio: ^5.0.1
  bloc: ^8.1.1
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  flutter_svg: ^2.0.7
  sqflite: ^2.2.8+4
  json_annotation: ^4.8.1
  geolocator: ^9.0.2
  geocoding: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.7.0
  build_runner: ^2.4.5
  flutter_native_splash: ^2.3.1

flutter_native_splash:
  image: assets/images/splash.png
  color: "#ffffff"


flutter:

  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/roboto/Roboto-Regular.ttf
        - asset: fonts/roboto/Roboto-Bold.ttf
    - family: Ubuntu
      fonts:
        - asset: fonts/ubuntu/Ubuntu-Regular.ttf
        - asset: fonts/ubuntu/Ubuntu-Medium.ttf
